### ISSUE TITLE
Issue on change pasword

### ISSUE THREAD

**Issue by grsofiane** [QuentinCG/OVH-Email-Manager-Website#3]
Hi,
thank you for this great job.
i have issue when i try to change the password of mail account.
the exception returned is : 
Client error: `POST https://api.ovh.com/1.0/email/domain/MYDOMAIN.com/account/MYACCOUNT/changePassword` resulted in a `409 ActionInProgress` response: {"message":"This pop is already being processed: MYACCOUNT@MYDOMAIN.com, please try later"}

Can you help me please.
Regards

**Comment by QuentinCG** [comment]
Hi Grsofiane,

Sorry for the late answer (I was travelling).
Is your problem solved or did you just give up?

If solved, could you explain where the problem was?
If not, could you explain a bit more your OVH API configuration and how you created your email addresses in the first place? (it would be easier to reproduce the problem)

Best regards,
Quentin CG
